# Generated by Django 5.1 on 2024-08-26 06:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Jogador",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("pontuacao", models.IntegerField(default=0)),
                ("acs", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Mapa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Tabela_de_jogadores",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pontos_total", models.IntegerField(default=50)),
                ("media_de_acs", models.IntegerField(default=0)),
                ("partidas_jogadas", models.IntegerField(default=0)),
                (
                    "acs_total",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="acs_total",
                        to="torneios.jogador",
                    ),
                ),
                (
                    "nickname",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nickname",
                        to="torneios.jogador",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Time",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vencedor", models.BooleanField()),
                (
                    "jogador1",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jogador1",
                        to="torneios.jogador",
                    ),
                ),
                (
                    "jogador2",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jogador2",
                        to="torneios.jogador",
                    ),
                ),
                (
                    "jogador3",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jogador3",
                        to="torneios.jogador",
                    ),
                ),
                (
                    "jogador4",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jogador4",
                        to="torneios.jogador",
                    ),
                ),
                (
                    "jogador5",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jogador5",
                        to="torneios.jogador",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Tabela_de_partidas",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.DateField()),
                (
                    "mapa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="torneios.mapa"
                    ),
                ),
                (
                    "time1",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="time1",
                        to="torneios.time",
                    ),
                ),
                (
                    "time2",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="time2",
                        to="torneios.time",
                    ),
                ),
            ],
        ),
    ]
