# Generated by Django 5.1 on 2024-08-25 07:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Mapa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Player",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=200)),
                ("pontos_totais", models.IntegerField(default=50)),
                ("partidas_jogadas", models.IntegerField(default=0)),
                ("acs", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Partida",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("time_1", models.CharField(max_length=100)),
                ("time_2", models.CharField(max_length=100)),
                ("placar_time_1", models.IntegerField(default=0)),
                ("placar_time_2", models.IntegerField(default=0)),
                (
                    "mapa_jogado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="players.mapa"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="JogadorPartida",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "jogador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="players.player"
                    ),
                ),
            ],
        ),
    ]
