# Generated by Django 5.1 on 2024-08-26 04:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Mapa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Menu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=200)),
                ("link", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Player",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("pontos_totais", models.IntegerField(default=0)),
                ("acs", models.IntegerField(default=0)),
                ("partidas_jogadas", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Partida",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("placar_time_1", models.IntegerField(default=0)),
                ("placar_time_2", models.IntegerField(default=0)),
                (
                    "mapa_jogado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="players.mapa"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="JogadorPartida",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("acs", models.IntegerField(default=0)),
                ("pontos_partida", models.IntegerField(default=0)),
                (
                    "partida",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="players.partida",
                    ),
                ),
                (
                    "jogador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="players.player"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Time",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "jogador_1",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="time_jogador1",
                        to="players.player",
                    ),
                ),
                (
                    "jogador_2",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="time_jogador2",
                        to="players.player",
                    ),
                ),
                (
                    "jogador_3",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="time_jogador3",
                        to="players.player",
                    ),
                ),
                (
                    "jogador_4",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="time_jogador4",
                        to="players.player",
                    ),
                ),
                (
                    "jogador_5",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="time_jogador5",
                        to="players.player",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="partida",
            name="time_1",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="partidas_como_time1",
                to="players.time",
            ),
        ),
        migrations.AddField(
            model_name="partida",
            name="time_2",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="partidas_como_time2",
                to="players.time",
            ),
        ),
    ]
